### ISSUE TITLE
OS X support?

### ISSUE THREAD

**Issue by saxoncameron** [bluaxees/Poricom#6]
Hey there! This looks like a really useful app. I see that there's only an `.exe` release for Windows, so I've tried building it locally on my Mac (Monterey 12.2.1 on a MacBook Pro 16" 2019, python `3.9.12`), but I get this error when attempting to run `main.py` in the `code` directory.

```
saxoncameron@sax code % python main.py
Traceback (most recent call last):
  File "/Users/saxoncameron/Sites/Poricom/code/main.py", line 24, in <module>
    from pyqtkeybind import keybinder
  File "/usr/local/lib/python3.9/site-packages/pyqtkeybind/__init__.py", line 11, in <module>
    from .x11 import X11KeyBinder
  File "/usr/local/lib/python3.9/site-packages/pyqtkeybind/x11/__init__.py", line 6, in <module>
    from PyQt5.QtX11Extras import QX11Info
ModuleNotFoundError: No module named 'PyQt5.QtX11Extras'
```

Note this is after running `pip install -r requirements.txt` as per `README.md`.

I don't care so much about building this locally, I just want to be able to use it. Any chance you could make a release for OS X? Thanks!

**Comment by bluaxees** [comment]
Unfortunately the package I'm using to implement external capture only support Windows and Linux systems. For now, you may use [this branch](https://github.com/bluaxees/Poricom/tree/feature/osx-support) to run the program in macOS. Note that this is only a band-aid fix and will disable the shortcut for external captures. 
Still, you may use the external capture button under the FILE tab to perform OCR on images outside the application.

**Comment by saxoncameron** [comment]
Thanks for the quick response!

I tried out the branch `osx-support` and was able to run the application, however it doesn't appear to function correctly which I must surmise is a platform problem. In the ensuing comments I will log my problems one by one with attached videos, as I hope that will help:

**Comment by saxoncameron** [comment]
When attempting to open a `.cbz` file, it does not load, and if I had to guess, it's because the contents of the zip are in a series of folders rather than just a flat root of images.

If I unzip it and open one of those folders, it loads fine. See video example:

https://www.dropbox.com/s/980azkynwsjkx7t/cbz%20loading.mov?dl=0

**Comment by saxoncameron** [comment]
Text selection OCR as per the README demo videos doesn't work for me at all unfortunately :( Neither with manga ocr or with tesseract vertical or horizontal. Video example:

https://www.dropbox.com/s/qs9jevz42dv1v59/ocr%20not%20working.mov?dl=0

**Comment by saxoncameron** [comment]
Other suggestions:

- It'd be VERY useful if OCR parsings were copied to the system clipboard so the results could be used with texthooker/clipboard applications, e.g. for parsing with Yomichan/Migaku
  - Without this, the program unfortunately wouldn't be useful for me even if the OCR was working
- This prompt comes up on every load, and also when switching from tesseract back to -> manga ocr. It'd be nicer if it loaded just once, and thereafter was aware of it being cached.
  - ![image](https://user-images.githubusercontent.com/3240185/164614928-b64fa63b-9bc4-4375-a4a2-540830d94852.png)
- It'd be great if you could minimise this sidebar
  - ![Pasted_Image_22_4_2022__4_18_pm](https://user-images.githubusercontent.com/3240185/164614987-8b7e2476-39f0-4f4c-a9a8-e556d4c56663.png)
- It'd be nice if you could use these controls with standard keyboard hotkeys, like ctrl/cmd +- for zoom, and left/right arrow keys for page navigation
  - ![image](https://user-images.githubusercontent.com/3240185/164615129-0eaa9561-4df6-4592-ac3c-3e38b0127d27.png)
- It'd be ideal if the open dialog remembered the last directory that you opened from, rather than not doing so.
  - ![Pasted_Image_22_4_2022__4_21_pm](https://user-images.githubusercontent.com/3240185/164615557-15815fbd-05ce-451e-89ce-92a85752e08d.png)
- The options in dropdown menus in many of the setting dialogs are often cut-off
  - ![image](https://user-images.githubusercontent.com/3240185/164615681-2427dd50-7057-4fe0-8185-b5ae8ae6b022.png)
- Although you can scroll through pages, with my trackpad I'm finding it way too sensitive. Even a small scroll navigates me ahead several pages. Increasing the scroll length required for multi-page navigation would be nice, as most users will only want to scroll one page at a time forward/backwards

**Comment by saxoncameron** [comment]
Thank you fro your efforts on this application so far - it's the first implementation of a GUI that I've seen for manga OCR, which is the best performing OCR I've used to date. With just a few changes and improvements this is something I can see myself using frequently for reading manga.

Hope this helps! Let me know if you'd like me to test any future changes or fixes. Thanks!

**Comment by bluaxees** [comment]
> Text selection OCR as per the README demo videos doesn't work for me at all unfortunately :( Neither with manga ocr or with tesseract vertical or horizontal. Video example:
> 
> https://www.dropbox.com/s/qs9jevz42dv1v59/ocr%20not%20working.mov?dl=0

You have to hold the mouse button to show the detected text. Releasing the mouse button will hide the preview, which is what's happening here in your video. 

> It'd be VERY useful if OCR parsings were copied to the system clipboard

This is the default behavior, at least in Windows. Let me know if the text is being copied in the macOS clipboard once you've tried the above method.

> When attempting to open a .cbz file, it does not load, and if I had to guess, it's because the contents of the zip are in a series of folders rather than just a flat root of images.

You are correct. My understanding of comic book archives is that they contain images only, which is why I implemented it to read only image files from directories/archives.

> Although you can scroll through pages, with my trackpad I'm finding it way too sensitive.

Oops.. Just tested this on my laptop and I'm getting the same behavior. I completely forgot to test this. I will release a hotfix soon. For now, just use a mouse if you have one.

> The options in dropdown menus in many of the setting dialogs are often cut-off

I'm not sure if this issue is unique to macOS. I will test this once I setup an macOS VM. Not promising anything though.

**Comment by bluaxees** [comment]
Thank you for your suggestions! I will compile them in this comment with some notes.
- **Display directories containing images** - This was the previous behavior as you can see in the [v0.2.0 demo](https://user-images.githubusercontent.com/45705751/161960776-da608849-c80d-4bb9-be9f-11e40b4c3160.mp4). I might bring it back given that some archives may contain only folders.
- **Remove load model prompt** - Might be difficult. I have no idea how HuggingFace names and stores model so it's difficult to track whether the model is already in cache.
- **Option to hide explorer/sidebar** 
- **Navigation using keyboard** 
- **Remember last path in file dialogs**
- **Fix truncated dropdown menu** - See comment above
- **Adjust scrolling using trackpad** - Hotfix soon

I will be busy for quite some time so expect these features in a much later date.

**Comment by saxoncameron** [comment]
Thanks for your responses and summaries! It's working for me locally after you clarified mouse selection behaviour.

Looking forward to future features and improvements :)

**Comment by AhnafS** [comment]
Hello, can you tell me how to run this on mac os?

**Comment by bluaxees** [comment]
@AhnafS follow the developer's guide under installation:

> For developers, clone this repo and install requirements: `pip install -r requirements.txt`. Run the app in the command line using `python main.py`

Note that the global shortcut does not work for OSX

**Comment by AhnafS** [comment]
after much trial and error, it seems like this does not completely work with the M1 MacBooks 🥲

**Comment by bluaxees** [comment]
@AhnafS There should be a [branch for OSX](https://github.com/bluaxees/Poricom/tree/feature/osx-support). If this doesn't work, then it might be an M1 compatibility issue

**Comment by AhnafS** [comment]
Yes thank you, I found a workaround for M1 users. If you have an M1 mac, then your ARM64 arch won't work on this project with python. Thus, you must create an x86 python env. To do this, I made a conda x86 env with Python 3.9.9. Then you can clone the project and download all the requirements. When downloading and running the project on the branch for OSX, you will still face some issues with a few libraries, but a simple google search can fix that :)

**Comment by Tenpi** [comment]
> Yes thank you, I found a workaround for M1 users. If you have an M1 mac, then your ARM64 arch won't work on this project with python. Thus, you must create an x86 python env. To do this, I made a conda x86 env with Python 3.9.9. Then you can clone the project and download all the requirements. When downloading and running the project on the branch for OSX, you will still face some issues with a few libraries, but a simple google search can fix that :)

How did you fix this error with tesserocr on Mac M1 (I am using x86 python)
```
Traceback (most recent call last):
  File "/Users/chris/Documents/Git Clone/Poricom/code/main.py", line 24, in <module>
    from MainWindow import MainWindow
  File "/Users/chris/Documents/Git Clone/Poricom/code/MainWindow.py", line 29, in <module>
    from utils.image_io import mangaFileToImageDir
  File "/Users/chris/Documents/Git Clone/Poricom/code/utils/image_io.py", line 26, in <module>
    from tesserocr import PyTessBaseAPI
ImportError: dlopen(/Users/chris/.pyenv/versions/3.9.9/lib/python3.9/site-packages/tesserocr.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (__ZN9tesseract11TessBaseAPI10GetBoxTextEi)
```

**Comment by AhnafS** [comment]
> > Yes thank you, I found a workaround for M1 users. If you have an M1 mac, then your ARM64 arch won't work on this project with python. Thus, you must create an x86 python env. To do this, I made a conda x86 env with Python 3.9.9. Then you can clone the project and download all the requirements. When downloading and running the project on the branch for OSX, you will still face some issues with a few libraries, but a simple google search can fix that :)
> 
> How did you fix this error with tesserocr on Mac M1 (I am using x86 python)
> 
> ```
> Traceback (most recent call last):
>   File "/Users/chris/Documents/Git Clone/Poricom/code/main.py", line 24, in <module>
>     from MainWindow import MainWindow
>   File "/Users/chris/Documents/Git Clone/Poricom/code/MainWindow.py", line 29, in <module>
>     from utils.image_io import mangaFileToImageDir
>   File "/Users/chris/Documents/Git Clone/Poricom/code/utils/image_io.py", line 26, in <module>
>     from tesserocr import PyTessBaseAPI
> ImportError: dlopen(/Users/chris/.pyenv/versions/3.9.9/lib/python3.9/site-packages/tesserocr.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (__ZN9tesseract11TessBaseAPI10GetBoxTextEi)
> ```

I remember having this same problem, I googled it and this issue thread helped me out a lot.
https://github.com/sirfz/tesserocr/issues/9
You should try doing `pip3 install cython tesseract-ocr libtesseract-dev libleptonica-dev `

**Comment by Tenpi** [comment]
> You should try doing `pip3 install cython tesseract-ocr libtesseract-dev libleptonica-dev `

I installed these with brew (since these are linux packages, not python), but it still hasn't resolved my issue.

Since you got this to compile on M1 Macs would you mind packaging it into an app? You could probably use [PyInstaller](https://pyinstaller.org/en/stable/).

**Comment by AhnafS** [comment]
> > You should try doing `pip3 install cython tesseract-ocr libtesseract-dev libleptonica-dev `
> 
> I installed these with brew (since these are linux packages, not python), but it still hasn't resolved my issue.
> 
> Since you got this to compile on M1 Macs would you mind packaging it into an app? You could probably use [PyInstaller](https://pyinstaller.org/en/stable/).

Im very new to python, so it will take a little while. But I just did a fresh download again, and got this same error. If you do `conda install tesserocr` it should work

**Comment by Tenpi** [comment]
> Im very new to python, so it will take a little while. But I just did a fresh download again, and got this same error. If you do `conda install tesserocr` it should work

I understand I haven't got this working but I am going to use [mokuro](https://github.com/kha-white/mokuro) as an alternative instead, it OCR's every page and creates html files to read in a browser which works for me, and compiles fine with x86 python.
